// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/study/networkprogram/proto/MsgProto.proto

package com.study.networkprogram.proto;

public final class MsgProto {
  private MsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string msgId = 1;</code>
     */
    java.lang.String getMsgId();
    /**
     * <code>string msgId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    /**
     * <code>string msgType = 2;</code>
     */
    java.lang.String getMsgType();
    /**
     * <code>string msgType = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgTypeBytes();

    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */
    int getExtendCount();
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */
    boolean containsExtend(
        java.lang.String key);
    /**
     * Use {@link #getExtendMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getExtend();
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getExtendMap();
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    java.lang.String getExtendOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    java.lang.String getExtendOrThrow(
        java.lang.String key);

    /**
     * <code>.User fromUser = 4;</code>
     */
    boolean hasFromUser();
    /**
     * <code>.User fromUser = 4;</code>
     */
    com.study.networkprogram.proto.MsgProto.User getFromUser();
    /**
     * <code>.User fromUser = 4;</code>
     */
    com.study.networkprogram.proto.MsgProto.UserOrBuilder getFromUserOrBuilder();

    /**
     * <code>.User toUser = 5;</code>
     */
    boolean hasToUser();
    /**
     * <code>.User toUser = 5;</code>
     */
    com.study.networkprogram.proto.MsgProto.User getToUser();
    /**
     * <code>.User toUser = 5;</code>
     */
    com.study.networkprogram.proto.MsgProto.UserOrBuilder getToUserOrBuilder();
  }
  /**
   * Protobuf type {@code Msg}
   */
  public  static final class Msg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Msg)
      MsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Msg.newBuilder() to construct.
    private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Msg() {
      msgId_ = "";
      msgType_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              msgId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msgType_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                extend_ = com.google.protobuf.MapField.newMapField(
                    ExtendDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              extend__ = input.readMessage(
                  ExtendDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              extend_.getMutableMap().put(
                  extend__.getKey(), extend__.getValue());
              break;
            }
            case 34: {
              com.study.networkprogram.proto.MsgProto.User.Builder subBuilder = null;
              if (fromUser_ != null) {
                subBuilder = fromUser_.toBuilder();
              }
              fromUser_ = input.readMessage(com.study.networkprogram.proto.MsgProto.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fromUser_);
                fromUser_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.study.networkprogram.proto.MsgProto.User.Builder subBuilder = null;
              if (toUser_ != null) {
                subBuilder = toUser_.toBuilder();
              }
              toUser_ = input.readMessage(com.study.networkprogram.proto.MsgProto.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(toUser_);
                toUser_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.study.networkprogram.proto.MsgProto.internal_static_Msg_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetExtend();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.study.networkprogram.proto.MsgProto.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.study.networkprogram.proto.MsgProto.Msg.class, com.study.networkprogram.proto.MsgProto.Msg.Builder.class);
    }

    private int bitField0_;
    public static final int MSGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object msgId_;
    /**
     * <code>string msgId = 1;</code>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      }
    }
    /**
     * <code>string msgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object msgType_;
    /**
     * <code>string msgType = 2;</code>
     */
    public java.lang.String getMsgType() {
      java.lang.Object ref = msgType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgType_ = s;
        return s;
      }
    }
    /**
     * <code>string msgType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgTypeBytes() {
      java.lang.Object ref = msgType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTEND_FIELD_NUMBER = 3;
    private static final class ExtendDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.study.networkprogram.proto.MsgProto.internal_static_Msg_ExtendEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> extend_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetExtend() {
      if (extend_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtendDefaultEntryHolder.defaultEntry);
      }
      return extend_;
    }

    public int getExtendCount() {
      return internalGetExtend().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    public boolean containsExtend(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetExtend().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtendMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtend() {
      return getExtendMap();
    }
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getExtendMap() {
      return internalGetExtend().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    public java.lang.String getExtendOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtend().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; extend = 3;</code>
     */

    public java.lang.String getExtendOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtend().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int FROMUSER_FIELD_NUMBER = 4;
    private com.study.networkprogram.proto.MsgProto.User fromUser_;
    /**
     * <code>.User fromUser = 4;</code>
     */
    public boolean hasFromUser() {
      return fromUser_ != null;
    }
    /**
     * <code>.User fromUser = 4;</code>
     */
    public com.study.networkprogram.proto.MsgProto.User getFromUser() {
      return fromUser_ == null ? com.study.networkprogram.proto.MsgProto.User.getDefaultInstance() : fromUser_;
    }
    /**
     * <code>.User fromUser = 4;</code>
     */
    public com.study.networkprogram.proto.MsgProto.UserOrBuilder getFromUserOrBuilder() {
      return getFromUser();
    }

    public static final int TOUSER_FIELD_NUMBER = 5;
    private com.study.networkprogram.proto.MsgProto.User toUser_;
    /**
     * <code>.User toUser = 5;</code>
     */
    public boolean hasToUser() {
      return toUser_ != null;
    }
    /**
     * <code>.User toUser = 5;</code>
     */
    public com.study.networkprogram.proto.MsgProto.User getToUser() {
      return toUser_ == null ? com.study.networkprogram.proto.MsgProto.User.getDefaultInstance() : toUser_;
    }
    /**
     * <code>.User toUser = 5;</code>
     */
    public com.study.networkprogram.proto.MsgProto.UserOrBuilder getToUserOrBuilder() {
      return getToUser();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMsgIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgId_);
      }
      if (!getMsgTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgType_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetExtend(),
          ExtendDefaultEntryHolder.defaultEntry,
          3);
      if (fromUser_ != null) {
        output.writeMessage(4, getFromUser());
      }
      if (toUser_ != null) {
        output.writeMessage(5, getToUser());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMsgIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgId_);
      }
      if (!getMsgTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgType_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetExtend().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        extend__ = ExtendDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, extend__);
      }
      if (fromUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getFromUser());
      }
      if (toUser_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getToUser());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.study.networkprogram.proto.MsgProto.Msg)) {
        return super.equals(obj);
      }
      com.study.networkprogram.proto.MsgProto.Msg other = (com.study.networkprogram.proto.MsgProto.Msg) obj;

      if (!getMsgId()
          .equals(other.getMsgId())) return false;
      if (!getMsgType()
          .equals(other.getMsgType())) return false;
      if (!internalGetExtend().equals(
          other.internalGetExtend())) return false;
      if (hasFromUser() != other.hasFromUser()) return false;
      if (hasFromUser()) {
        if (!getFromUser()
            .equals(other.getFromUser())) return false;
      }
      if (hasToUser() != other.hasToUser()) return false;
      if (hasToUser()) {
        if (!getToUser()
            .equals(other.getToUser())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType().hashCode();
      if (!internalGetExtend().getMap().isEmpty()) {
        hash = (37 * hash) + EXTEND_FIELD_NUMBER;
        hash = (53 * hash) + internalGetExtend().hashCode();
      }
      if (hasFromUser()) {
        hash = (37 * hash) + FROMUSER_FIELD_NUMBER;
        hash = (53 * hash) + getFromUser().hashCode();
      }
      if (hasToUser()) {
        hash = (37 * hash) + TOUSER_FIELD_NUMBER;
        hash = (53 * hash) + getToUser().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.networkprogram.proto.MsgProto.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.study.networkprogram.proto.MsgProto.Msg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Msg)
        com.study.networkprogram.proto.MsgProto.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.study.networkprogram.proto.MsgProto.internal_static_Msg_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetExtend();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableExtend();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.study.networkprogram.proto.MsgProto.internal_static_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.study.networkprogram.proto.MsgProto.Msg.class, com.study.networkprogram.proto.MsgProto.Msg.Builder.class);
      }

      // Construct using com.study.networkprogram.proto.MsgProto.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        msgId_ = "";

        msgType_ = "";

        internalGetMutableExtend().clear();
        if (fromUserBuilder_ == null) {
          fromUser_ = null;
        } else {
          fromUser_ = null;
          fromUserBuilder_ = null;
        }
        if (toUserBuilder_ == null) {
          toUser_ = null;
        } else {
          toUser_ = null;
          toUserBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.study.networkprogram.proto.MsgProto.internal_static_Msg_descriptor;
      }

      @java.lang.Override
      public com.study.networkprogram.proto.MsgProto.Msg getDefaultInstanceForType() {
        return com.study.networkprogram.proto.MsgProto.Msg.getDefaultInstance();
      }

      @java.lang.Override
      public com.study.networkprogram.proto.MsgProto.Msg build() {
        com.study.networkprogram.proto.MsgProto.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.study.networkprogram.proto.MsgProto.Msg buildPartial() {
        com.study.networkprogram.proto.MsgProto.Msg result = new com.study.networkprogram.proto.MsgProto.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.msgId_ = msgId_;
        result.msgType_ = msgType_;
        result.extend_ = internalGetExtend();
        result.extend_.makeImmutable();
        if (fromUserBuilder_ == null) {
          result.fromUser_ = fromUser_;
        } else {
          result.fromUser_ = fromUserBuilder_.build();
        }
        if (toUserBuilder_ == null) {
          result.toUser_ = toUser_;
        } else {
          result.toUser_ = toUserBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.study.networkprogram.proto.MsgProto.Msg) {
          return mergeFrom((com.study.networkprogram.proto.MsgProto.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.study.networkprogram.proto.MsgProto.Msg other) {
        if (other == com.study.networkprogram.proto.MsgProto.Msg.getDefaultInstance()) return this;
        if (!other.getMsgId().isEmpty()) {
          msgId_ = other.msgId_;
          onChanged();
        }
        if (!other.getMsgType().isEmpty()) {
          msgType_ = other.msgType_;
          onChanged();
        }
        internalGetMutableExtend().mergeFrom(
            other.internalGetExtend());
        if (other.hasFromUser()) {
          mergeFromUser(other.getFromUser());
        }
        if (other.hasToUser()) {
          mergeToUser(other.getToUser());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.study.networkprogram.proto.MsgProto.Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.study.networkprogram.proto.MsgProto.Msg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object msgId_ = "";
      /**
       * <code>string msgId = 1;</code>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>string msgId = 1;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgType_ = "";
      /**
       * <code>string msgType = 2;</code>
       */
      public java.lang.String getMsgType() {
        java.lang.Object ref = msgType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgTypeBytes() {
        java.lang.Object ref = msgType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgType = 2;</code>
       */
      public Builder setMsgType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgType = 2;</code>
       */
      public Builder clearMsgType() {
        
        msgType_ = getDefaultInstance().getMsgType();
        onChanged();
        return this;
      }
      /**
       * <code>string msgType = 2;</code>
       */
      public Builder setMsgTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> extend_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetExtend() {
        if (extend_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ExtendDefaultEntryHolder.defaultEntry);
        }
        return extend_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableExtend() {
        onChanged();;
        if (extend_ == null) {
          extend_ = com.google.protobuf.MapField.newMapField(
              ExtendDefaultEntryHolder.defaultEntry);
        }
        if (!extend_.isMutable()) {
          extend_ = extend_.copy();
        }
        return extend_;
      }

      public int getExtendCount() {
        return internalGetExtend().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public boolean containsExtend(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetExtend().getMap().containsKey(key);
      }
      /**
       * Use {@link #getExtendMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getExtend() {
        return getExtendMap();
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getExtendMap() {
        return internalGetExtend().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public java.lang.String getExtendOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExtend().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public java.lang.String getExtendOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetExtend().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearExtend() {
        internalGetMutableExtend().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public Builder removeExtend(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExtend().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableExtend() {
        return internalGetMutableExtend().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */
      public Builder putExtend(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableExtend().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; extend = 3;</code>
       */

      public Builder putAllExtend(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableExtend().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.study.networkprogram.proto.MsgProto.User fromUser_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.study.networkprogram.proto.MsgProto.User, com.study.networkprogram.proto.MsgProto.User.Builder, com.study.networkprogram.proto.MsgProto.UserOrBuilder> fromUserBuilder_;
      /**
       * <code>.User fromUser = 4;</code>
       */
      public boolean hasFromUser() {
        return fromUserBuilder_ != null || fromUser_ != null;
      }
      /**
       * <code>.User fromUser = 4;</code>
       */
      public com.study.networkprogram.proto.MsgProto.User getFromUser() {
        if (fromUserBuilder_ == null) {
          return fromUser_ == null ? com.study.networkprogram.proto.MsgProto.User.getDefaultInstance() : fromUser_;
        } else {
          return fromUserBuilder_.getMessage();
        }
      }
      /**
       * <code>.User fromUser = 4;</code>
       */
      public Builder setFromUser(com.study.networkprogram.proto.MsgProto.User value) {
        if (fromUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fromUser_ = value;
          onChanged();
        } else {
          fromUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.User fromUser = 4;</code>
       */
      public Builder setFromUser(
          com.study.networkprogram.proto.MsgProto.User.Builder builderForValue) {
        if (fromUserBuilder_ == null) {
          fromUser_ = builderForValue.build();
          onChanged();
        } else {
          fromUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.User fromUser = 4;</code>
       */
      public Builder mergeFromUser(com.study.networkprogram.proto.MsgProto.User value) {
        if (fromUserBuilder_ == null) {
          if (fromUser_ != null) {
            fromUser_ =
              com.study.networkprogram.proto.MsgProto.User.newBuilder(fromUser_).mergeFrom(value).buildPartial();
          } else {
            fromUser_ = value;
          }
          onChanged();
        } else {
          fromUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.User fromUser = 4;</code>
       */
      public Builder clearFromUser() {
        if (fromUserBuilder_ == null) {
          fromUser_ = null;
          onChanged();
        } else {
          fromUser_ = null;
          fromUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.User fromUser = 4;</code>
       */
      public com.study.networkprogram.proto.MsgProto.User.Builder getFromUserBuilder() {
        
        onChanged();
        return getFromUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.User fromUser = 4;</code>
       */
      public com.study.networkprogram.proto.MsgProto.UserOrBuilder getFromUserOrBuilder() {
        if (fromUserBuilder_ != null) {
          return fromUserBuilder_.getMessageOrBuilder();
        } else {
          return fromUser_ == null ?
              com.study.networkprogram.proto.MsgProto.User.getDefaultInstance() : fromUser_;
        }
      }
      /**
       * <code>.User fromUser = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.study.networkprogram.proto.MsgProto.User, com.study.networkprogram.proto.MsgProto.User.Builder, com.study.networkprogram.proto.MsgProto.UserOrBuilder> 
          getFromUserFieldBuilder() {
        if (fromUserBuilder_ == null) {
          fromUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.study.networkprogram.proto.MsgProto.User, com.study.networkprogram.proto.MsgProto.User.Builder, com.study.networkprogram.proto.MsgProto.UserOrBuilder>(
                  getFromUser(),
                  getParentForChildren(),
                  isClean());
          fromUser_ = null;
        }
        return fromUserBuilder_;
      }

      private com.study.networkprogram.proto.MsgProto.User toUser_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.study.networkprogram.proto.MsgProto.User, com.study.networkprogram.proto.MsgProto.User.Builder, com.study.networkprogram.proto.MsgProto.UserOrBuilder> toUserBuilder_;
      /**
       * <code>.User toUser = 5;</code>
       */
      public boolean hasToUser() {
        return toUserBuilder_ != null || toUser_ != null;
      }
      /**
       * <code>.User toUser = 5;</code>
       */
      public com.study.networkprogram.proto.MsgProto.User getToUser() {
        if (toUserBuilder_ == null) {
          return toUser_ == null ? com.study.networkprogram.proto.MsgProto.User.getDefaultInstance() : toUser_;
        } else {
          return toUserBuilder_.getMessage();
        }
      }
      /**
       * <code>.User toUser = 5;</code>
       */
      public Builder setToUser(com.study.networkprogram.proto.MsgProto.User value) {
        if (toUserBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          toUser_ = value;
          onChanged();
        } else {
          toUserBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.User toUser = 5;</code>
       */
      public Builder setToUser(
          com.study.networkprogram.proto.MsgProto.User.Builder builderForValue) {
        if (toUserBuilder_ == null) {
          toUser_ = builderForValue.build();
          onChanged();
        } else {
          toUserBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.User toUser = 5;</code>
       */
      public Builder mergeToUser(com.study.networkprogram.proto.MsgProto.User value) {
        if (toUserBuilder_ == null) {
          if (toUser_ != null) {
            toUser_ =
              com.study.networkprogram.proto.MsgProto.User.newBuilder(toUser_).mergeFrom(value).buildPartial();
          } else {
            toUser_ = value;
          }
          onChanged();
        } else {
          toUserBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.User toUser = 5;</code>
       */
      public Builder clearToUser() {
        if (toUserBuilder_ == null) {
          toUser_ = null;
          onChanged();
        } else {
          toUser_ = null;
          toUserBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.User toUser = 5;</code>
       */
      public com.study.networkprogram.proto.MsgProto.User.Builder getToUserBuilder() {
        
        onChanged();
        return getToUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.User toUser = 5;</code>
       */
      public com.study.networkprogram.proto.MsgProto.UserOrBuilder getToUserOrBuilder() {
        if (toUserBuilder_ != null) {
          return toUserBuilder_.getMessageOrBuilder();
        } else {
          return toUser_ == null ?
              com.study.networkprogram.proto.MsgProto.User.getDefaultInstance() : toUser_;
        }
      }
      /**
       * <code>.User toUser = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.study.networkprogram.proto.MsgProto.User, com.study.networkprogram.proto.MsgProto.User.Builder, com.study.networkprogram.proto.MsgProto.UserOrBuilder> 
          getToUserFieldBuilder() {
        if (toUserBuilder_ == null) {
          toUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.study.networkprogram.proto.MsgProto.User, com.study.networkprogram.proto.MsgProto.User.Builder, com.study.networkprogram.proto.MsgProto.UserOrBuilder>(
                  getToUser(),
                  getParentForChildren(),
                  isClean());
          toUser_ = null;
        }
        return toUserBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Msg)
    }

    // @@protoc_insertion_point(class_scope:Msg)
    private static final com.study.networkprogram.proto.MsgProto.Msg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.study.networkprogram.proto.MsgProto.Msg();
    }

    public static com.study.networkprogram.proto.MsgProto.Msg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Msg>
        PARSER = new com.google.protobuf.AbstractParser<Msg>() {
      @java.lang.Override
      public Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Msg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Msg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.study.networkprogram.proto.MsgProto.Msg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string rid = 1;</code>
     */
    java.lang.String getRid();
    /**
     * <code>string rid = 1;</code>
     */
    com.google.protobuf.ByteString
        getRidBytes();

    /**
     * <code>string uid = 2;</code>
     */
    java.lang.String getUid();
    /**
     * <code>string uid = 2;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string img = 4;</code>
     */
    java.lang.String getImg();
    /**
     * <code>string img = 4;</code>
     */
    com.google.protobuf.ByteString
        getImgBytes();
  }
  /**
   * Protobuf type {@code User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      rid_ = "";
      uid_ = "";
      name_ = "";
      img_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              rid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              img_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.study.networkprogram.proto.MsgProto.internal_static_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.study.networkprogram.proto.MsgProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.study.networkprogram.proto.MsgProto.User.class, com.study.networkprogram.proto.MsgProto.User.Builder.class);
    }

    public static final int RID_FIELD_NUMBER = 1;
    private volatile java.lang.Object rid_;
    /**
     * <code>string rid = 1;</code>
     */
    public java.lang.String getRid() {
      java.lang.Object ref = rid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rid_ = s;
        return s;
      }
    }
    /**
     * <code>string rid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRidBytes() {
      java.lang.Object ref = rid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UID_FIELD_NUMBER = 2;
    private volatile java.lang.Object uid_;
    /**
     * <code>string uid = 2;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMG_FIELD_NUMBER = 4;
    private volatile java.lang.Object img_;
    /**
     * <code>string img = 4;</code>
     */
    public java.lang.String getImg() {
      java.lang.Object ref = img_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        img_ = s;
        return s;
      }
    }
    /**
     * <code>string img = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImgBytes() {
      java.lang.Object ref = img_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        img_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rid_);
      }
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getImgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, img_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rid_);
      }
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uid_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getImgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, img_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.study.networkprogram.proto.MsgProto.User)) {
        return super.equals(obj);
      }
      com.study.networkprogram.proto.MsgProto.User other = (com.study.networkprogram.proto.MsgProto.User) obj;

      if (!getRid()
          .equals(other.getRid())) return false;
      if (!getUid()
          .equals(other.getUid())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getImg()
          .equals(other.getImg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RID_FIELD_NUMBER;
      hash = (53 * hash) + getRid().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + IMG_FIELD_NUMBER;
      hash = (53 * hash) + getImg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.study.networkprogram.proto.MsgProto.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.study.networkprogram.proto.MsgProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.study.networkprogram.proto.MsgProto.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.study.networkprogram.proto.MsgProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.study.networkprogram.proto.MsgProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.study.networkprogram.proto.MsgProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.study.networkprogram.proto.MsgProto.User.class, com.study.networkprogram.proto.MsgProto.User.Builder.class);
      }

      // Construct using com.study.networkprogram.proto.MsgProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rid_ = "";

        uid_ = "";

        name_ = "";

        img_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.study.networkprogram.proto.MsgProto.internal_static_User_descriptor;
      }

      @java.lang.Override
      public com.study.networkprogram.proto.MsgProto.User getDefaultInstanceForType() {
        return com.study.networkprogram.proto.MsgProto.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.study.networkprogram.proto.MsgProto.User build() {
        com.study.networkprogram.proto.MsgProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.study.networkprogram.proto.MsgProto.User buildPartial() {
        com.study.networkprogram.proto.MsgProto.User result = new com.study.networkprogram.proto.MsgProto.User(this);
        result.rid_ = rid_;
        result.uid_ = uid_;
        result.name_ = name_;
        result.img_ = img_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.study.networkprogram.proto.MsgProto.User) {
          return mergeFrom((com.study.networkprogram.proto.MsgProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.study.networkprogram.proto.MsgProto.User other) {
        if (other == com.study.networkprogram.proto.MsgProto.User.getDefaultInstance()) return this;
        if (!other.getRid().isEmpty()) {
          rid_ = other.rid_;
          onChanged();
        }
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getImg().isEmpty()) {
          img_ = other.img_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.study.networkprogram.proto.MsgProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.study.networkprogram.proto.MsgProto.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object rid_ = "";
      /**
       * <code>string rid = 1;</code>
       */
      public java.lang.String getRid() {
        java.lang.Object ref = rid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRidBytes() {
        java.lang.Object ref = rid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rid = 1;</code>
       */
      public Builder setRid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rid = 1;</code>
       */
      public Builder clearRid() {
        
        rid_ = getDefaultInstance().getRid();
        onChanged();
        return this;
      }
      /**
       * <code>string rid = 1;</code>
       */
      public Builder setRidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <code>string uid = 2;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 2;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object img_ = "";
      /**
       * <code>string img = 4;</code>
       */
      public java.lang.String getImg() {
        java.lang.Object ref = img_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          img_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string img = 4;</code>
       */
      public com.google.protobuf.ByteString
          getImgBytes() {
        java.lang.Object ref = img_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          img_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string img = 4;</code>
       */
      public Builder setImg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        img_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string img = 4;</code>
       */
      public Builder clearImg() {
        
        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      /**
       * <code>string img = 4;</code>
       */
      public Builder setImgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        img_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:User)
    }

    // @@protoc_insertion_point(class_scope:User)
    private static final com.study.networkprogram.proto.MsgProto.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.study.networkprogram.proto.MsgProto.User();
    }

    public static com.study.networkprogram.proto.MsgProto.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.study.networkprogram.proto.MsgProto.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_ExtendEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_ExtendEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-com/study/networkprogram/proto/MsgProt" +
      "o.proto\"\246\001\n\003Msg\022\r\n\005msgId\030\001 \001(\t\022\017\n\007msgTyp" +
      "e\030\002 \001(\t\022 \n\006extend\030\003 \003(\0132\020.Msg.ExtendEntr" +
      "y\022\027\n\010fromUser\030\004 \001(\0132\005.User\022\025\n\006toUser\030\005 \001" +
      "(\0132\005.User\032-\n\013ExtendEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t:\0028\001\";\n\004User\022\013\n\003rid\030\001 \001(\t\022\013\n" +
      "\003uid\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\013\n\003img\030\004 \001(\tB*\n" +
      "\036com.study.networkprogram.protoB\010MsgProt" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_descriptor,
        new java.lang.String[] { "MsgId", "MsgType", "Extend", "FromUser", "ToUser", });
    internal_static_Msg_ExtendEntry_descriptor =
      internal_static_Msg_descriptor.getNestedTypes().get(0);
    internal_static_Msg_ExtendEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_ExtendEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Rid", "Uid", "Name", "Img", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
